import type { Express } from "express";
import { createServer, type Server } from "http";
import { storage } from "./storage";
import { InsertAnalysis } from "@shared/schema";
import { z } from "zod";
import fetch from "node-fetch";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { log } from "./vite";

// PDF generation function
async function generatePDF(analysisId: number) {
  const analysis = await storage.getAnalysis(analysisId);
  if (!analysis) {
    throw new Error("Analysis not found");
  }

  // Create a new PDF document
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([600, 800]);
  const { width, height } = page.getSize();
  
  // Add content to the PDF
  const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  
  // Title
  page.drawText('BioLeaf Disease Analysis Report', {
    x: 50,
    y: height - 50,
    size: 24,
    font: helveticaBold,
    color: rgb(0.2, 0.6, 0.3)
  });
  
  // Date
  const dateString = new Date(analysis.analyzedAt).toLocaleDateString();
  page.drawText(`Date: ${dateString}`, {
    x: 50,
    y: height - 80,
    size: 12,
    font: helveticaFont
  });
  
  // Disease section
  page.drawText('Disease Information', {
    x: 50,
    y: height - 120,
    size: 16,
    font: helveticaBold,
    color: rgb(0.2, 0.6, 0.3)
  });
  
  page.drawText(`Name: ${analysis.diseaseName}`, {
    x: 50,
    y: height - 145,
    size: 12,
    font: helveticaBold
  });
  
  page.drawText(`Disease: ${analysis.diseaseDescription}`, {
    x: 50,
    y: height - 160,
    size: 12,
    font: helveticaBold
  });
  // Wrap long text
  const maxWidth = 500;
  let yPos = height - 170;
  let line = '';
  
  yPos -= 15;
  
  const severity = analysis.diseaseSeverity;
  let words = severity.split(' ');
  for (let i = 0; i < words.length; i++) {
    const testLine = line + words[i] + ' ';
    const textWidth = helveticaFont.widthOfTextAtSize(testLine, 12);
    
    if (textWidth > maxWidth) {
      page.drawText(line, {
        x: 50,
        y: yPos,
        size: 12,
        font: helveticaFont
      });
      line = words[i] + ' ';
      yPos -= 15;
    } else {
      line = testLine;
    }
  }

  page.drawText(line, {
    x: 50,
    y: yPos,
    size: 12,
    font: helveticaFont
  });

  yPos -= 30;
  
  // Treatment section
  page.drawText('Treatment Options', {
    x: 50,
    y: yPos,
    size: 16,
    font: helveticaBold,
    color: rgb(0.2, 0.6, 0.3)
  });
  
  yPos -= 25;
  
  for (const treatment of analysis.treatmentOptions) {
    page.drawText(`• ${treatment.title}`, {
      x: 50,
      y: yPos,
      size: 12,
      font: helveticaBold
    });
    
    yPos -= 15;
    
    // Wrap treatment description
    words = treatment.description.split(' ');
    line = '';
    
    for (let i = 0; i < words.length; i++) {
      const testLine = line + words[i] + ' ';
      const textWidth = helveticaFont.widthOfTextAtSize(testLine, 12);
      
      if (textWidth > maxWidth) {
        page.drawText(line, {
          x: 70,
          y: yPos,
          size: 12,
          font: helveticaFont
        });
        line = words[i] + ' ';
        yPos -= 15;
      } else {
        line = testLine;
      }
    }
    
    page.drawText(line, {
      x: 70,
      y: yPos,
      size: 12,
      font: helveticaFont
    });
    
    yPos -= 25;
  }
  
  // Prevention section
  page.drawText('Prevention Measures', {
    x: 50,
    y: yPos,
    size: 16,
    font: helveticaBold,
    color: rgb(0.2, 0.6, 0.3)
  });
  
  yPos -= 25;
  
  for (const prevention of analysis.preventionMeasures) {
    page.drawText(`• ${prevention.title}`, {
      x: 50,
      y: yPos,
      size: 12,
      font: helveticaBold
    });
    
    yPos -= 15;
    
    // Wrap prevention description
    words = prevention.description.split(' ');
    line = '';
    
    for (let i = 0; i < words.length; i++) {
      const testLine = line + words[i] + ' ';
      const textWidth = helveticaFont.widthOfTextAtSize(testLine, 12);
      
      if (textWidth > maxWidth) {
        page.drawText(line, {
          x: 70,
          y: yPos,
          size: 12,
          font: helveticaFont
        });
        line = words[i] + ' ';
        yPos -= 15;
      } else {
        line = testLine;
      }
    }
    
    page.drawText(line, {
      x: 70,
      y: yPos,
      size: 12,
      font: helveticaFont
    });
    
    yPos -= 25;
  }
  
  // Footer
  page.drawText('Generated by BioLeaf Plant Disease Detection System', {
    x: 50,
    y: 50,
    size: 10,
    font: helveticaFont,
    color: rgb(0.5, 0.5, 0.5)
  });
  
  // Serialize the PDF to bytes
  const pdfBytes = await pdfDoc.save();
  return pdfBytes;
}

export async function registerRoutes(app: Express): Promise<Server> {
  // Validate the image input
  const imageSchema = z.object({
    image: z.string().min(1, "Image data is required"),
  });

  // Analyze plant disease endpoint
  app.post("/api/analyze", async (req, res) => {
    try {
      const validation = imageSchema.safeParse(req.body);
      if (!validation.success) {
        return res.status(400).json({ message: "Invalid input", errors: validation.error.format() });
      }

      const { image } = validation.data;
      
      let flaskData;
      
      try {
        // Create an AbortController for timeout
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 10000); // 10 seconds timeout
        log(`-------->>>>>>>Hello`);
        // Try to forward the request to the Flask API
        const flaskResponse = await fetch("http://127.0.0.1:4005/api/analyze", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ image }),
          signal: controller.signal,
        });
        
        log(`-------->>>>>>>Bye`);
        // Clear the timeout
        clearTimeout(timeoutId);

        if (!flaskResponse.ok) {
          throw new Error(`Flask API error: ${flaskResponse.status}`);
        }

        flaskData = await flaskResponse.json() as {
          PlantDisease: {
            name: string;
            description: string;
            severity: string;
          };
          disease:{
            name: string;
            description: string;
          };
          treatment: {
            title: string;
            description: string;
            icon: string;
          }[];
          prevention: {
            title: string;
            description: string;
            icon: string;
          }[];
        };
        
        log(`Successfully processed image with Flask API`);
      } catch (error) {
        // If Flask API call fails, return an error - do not use mock data
        const flaskError = error as Error;
        log(`Flask API error: ${flaskError.message || 'Unknown error'}`);
        
        // Return a proper error response
        throw new Error(`Failed to process image analysis: ${flaskError.message || 'Unknown error'}`);
      }

      // Store the analysis in our database
      const analysis: InsertAnalysis = {
        imageUrl: image,
        diseaseName: flaskData.PlantDisease.name,
        diseaseDescription: flaskData.PlantDisease.description,
        diseaseSeverity: flaskData.disease.description,
        treatmentOptions: flaskData.treatment,
        preventionMeasures: flaskData.prevention,
      };

      const savedAnalysis = await storage.createAnalysis(analysis);

      // Format the response to match our client-side type
      const response = {
        id: savedAnalysis.id,
        imageUrl: savedAnalysis.imageUrl,
        disease: {
          name: savedAnalysis.diseaseName,
          description: savedAnalysis.diseaseDescription,
          severity: savedAnalysis.diseaseSeverity,
        },
        treatmentOptions: savedAnalysis.treatmentOptions,
        preventionMeasures: savedAnalysis.preventionMeasures,
        analyzedAt: savedAnalysis.analyzedAt.toISOString(),
      };

      res.json(response);
    } catch (error: any) {
      console.error("Analysis error:", error);
      res.status(500).json({ message: error.message || "Failed to analyze image" });
    }
  });

  // Get history of analyses
  app.get("/api/history", async (req, res) => {
    try {
      const analyses = await storage.getAllAnalyses();
      
      // Format the response to match our client-side types
      const response = analyses.map(analysis => ({
        id: analysis.id,
        imageUrl: analysis.imageUrl,
        disease: {
          name: analysis.diseaseName,
          description: analysis.diseaseDescription,
          severity: analysis.diseaseSeverity,
        },
        analyzedAt: analysis.analyzedAt.toISOString(),
      }));
      
      res.json(response);
    } catch (error: any) {
      console.error("History retrieval error:", error);
      res.status(500).json({ message: error.message || "Failed to retrieve history" });
    }
  });

  // Get specific analysis by ID
  app.get("/api/history/:id", async (req, res) => {
    try {
      const id = parseInt(req.params.id);
      if (isNaN(id)) {
        return res.status(400).json({ message: "Invalid analysis ID" });
      }

      const analysis = await storage.getAnalysis(id);
      if (!analysis) {
        return res.status(404).json({ message: "Analysis not found" });
      }

      // Format the response to match our client-side type
      const response = {
        id: analysis.id,
        imageUrl: analysis.imageUrl,
        disease: {
          name: analysis.diseaseName,
          description: analysis.diseaseDescription,
          severity: analysis.diseaseSeverity,
        },
        treatmentOptions: analysis.treatmentOptions,
        preventionMeasures: analysis.preventionMeasures,
        analyzedAt: analysis.analyzedAt.toISOString(),
      };

      res.json(response);
    } catch (error: any) {
      console.error("Analysis retrieval error:", error);
      res.status(500).json({ message: error.message || "Failed to retrieve analysis" });
    }
  });

  // Generate and download PDF report
  app.post("/api/generate-pdf", async (req, res) => {
    try {
      const { analysisId } = req.body;
      if (!analysisId || typeof analysisId !== 'number') {
        return res.status(400).json({ message: "Valid analysis ID is required" });
      }

      const pdfBytes = await generatePDF(analysisId);
      
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename=bioleaf-report-${analysisId}.pdf`);
      res.send(Buffer.from(pdfBytes));
    } catch (error: any) {
      console.error("PDF generation error:", error);
      res.status(500).json({ message: error.message || "Failed to generate PDF" });
    }
  });

  // Mock endpoint for testing when Flask API is not available
  app.post("/api/mock-analyze", async (req, res) => {
    try {
      const validation = imageSchema.safeParse(req.body);
      if (!validation.success) {
        return res.status(400).json({ message: "Invalid input", errors: validation.error.format() });
      }

      const { image } = validation.data;
      
      // Mock response data (for testing without Flask API)
      const mockData = {
        disease: {
          name: "Powdery Mildew",
          description: "A common fungal disease that affects a wide range of plants by forming a white powdery coating on leaves and stems.",
          severity: "Moderate"
        },
        treatment: [
          {
            title: "Fungicide Application",
            description: "Apply a fungicide spray to control the spread. Choose products containing sulfur or potassium bicarbonate for best results.",
            icon: "healing"
          },
          {
            title: "Prune Affected Areas",
            description: "Remove affected leaves and branches to prevent further infection. Dispose of pruned material away from healthy plants.",
            icon: "content_cut"
          },
          {
            title: "Organic Treatment",
            description: "Use neem oil as a natural remedy. Mix 2 tablespoons in 1 gallon of water and spray on affected areas weekly.",
            icon: "eco"
          }
        ],
        prevention: [
          {
            title: "Improve Air Circulation",
            description: "Space plants adequately to allow proper air movement around foliage. This reduces humidity and helps prevent fungal spores from settling.",
            icon: "air"
          },
          {
            title: "Avoid Overhead Watering",
            description: "Water at the base of plants to reduce moisture on leaves. Water early in the day so any splashed leaves can dry quickly.",
            icon: "water_drop"
          },
          {
            title: "Regular Inspection",
            description: "Inspect plants weekly for early signs of disease. Early detection allows for prompt intervention before widespread damage occurs.",
            icon: "visibility"
          }
        ]
      };

      // Store the analysis in our database
      const analysis: InsertAnalysis = {
        imageUrl: image,
        diseaseName: mockData.disease.name,
        diseaseDescription: mockData.disease.description,
        diseaseSeverity: mockData.disease.severity,
        treatmentOptions: mockData.treatment,
        preventionMeasures: mockData.prevention,
      };

      const savedAnalysis = await storage.createAnalysis(analysis);

      // Format the response to match our client-side type
      const response = {
        id: savedAnalysis.id,
        imageUrl: savedAnalysis.imageUrl,
        disease: {
          name: savedAnalysis.diseaseName,
          description: savedAnalysis.diseaseDescription,
          severity: savedAnalysis.diseaseSeverity,
        },
        treatmentOptions: savedAnalysis.treatmentOptions,
        preventionMeasures: savedAnalysis.preventionMeasures,
        analyzedAt: savedAnalysis.analyzedAt.toISOString(),
      };

      res.json(response);
    } catch (error: any) {
      console.error("Mock analysis error:", error);
      res.status(500).json({ message: error.message || "Failed to analyze image" });
    }
  });

  const httpServer = createServer(app);
  return httpServer;
};